# Generated by Django 4.1.5 on 2023-02-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mak', models.CharField(max_length=20, unique=True)),
                ('tenk', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat', models.CharField(max_length=20, unique=True)),
                ('tent', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='sinhvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masv', models.CharField(max_length=20, unique=True)),
                ('tensv', models.CharField(max_length=30)),
                ('lop', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='image')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.khoa')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.school')),
            ],
        ),
    ]
