# Generated by Django 4.1.5 on 2023-03-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='khoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinhviens', to='myapp.khoa'),
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinhviens', to='myapp.school'),
        ),
    ]
